const careKinds=[['visit','通院'],['trimming','トリミング'],['grooming','グルーミング']];
function isGrooming(e){return e?.type==='trimming'||e?.type==='grooming'}
function eventLabel(e){return careKinds.find(([key])=>key===(e.type||'visit'))?.[1]||'通院'}
function careFacilities(){return db.groomingFacilities||[]}
function petCareFacilities(pid=petId){return careFacilities().filter(item=>assignedTo(item,pid))}
function facilityName(id){return careFacilities().find(f=>f.id===id)?.name||'施設未登録'}
function eventPlace(e){return isGrooming(e)?facilityName(e.facility):hospital(e.hospital)}
function saveCareChange(change,message){const before=JSON.parse(JSON.stringify(db));change();if(!persist()){db=before;return false}render();toast(message);return true}
function lastCare(type){return plogs().find(l=>l.type===type&&l.date<=today())}
function groomingCard(){return`<section class="card section-space grooming-card"><div class="row between"><h3>トリミング・グルーミング</h3>${action('groom-record','利用を記録','link')}</div>${careKinds.slice(1).map(([type,label])=>{const last=lastCare(type);return`<div class="care-last"><div><b>${label}</b><p class="small muted">${last?`${fmt(last.date)} · ${esc(facilityName(last.facility))}`:'最終利用日：未登録'}</p></div>${last?`<span class="pill">${diff(last.date,today())===0?'今日':diff(last.date,today())+'日前'}</span>`:''}</div>`}).join('')}${action('groom-event',icon('plus')+'予定を追加','secondary')}</section>`}
function groomingSettings(){const p=pet(),items=petCareFacilities();return`<section class="card settings-block"><div class="row between"><div><h3>トリミング施設</h3><span class="small muted">${esc(p.name)}の登録</span></div>${action('groom-facility','＋ 追加','link')}</div>${items.map(f=>`<div class="hospital"><b>${esc(f.name)}</b><p class="small muted">${esc(f.phone||'')} ${esc(f.address||'')}</p>${f.memo?`<p class="small">${esc(f.memo)}</p>`:''}${action('groom-facility','編集','link',`data-id="${f.id}"`)}</div>`).join('')||'<p class="small muted">この子のトリミング施設は未登録です。</p>'}</section>${groomingCard()}`}
function groomingFacilityModal(id){const old=careFacilities().find(f=>f.id===id),selected=old?(Array.isArray(old.pets)&&old.pets.length?old.pets:db.pets.map(p=>p.id)):[petId];modal(old?'施設を編集':'トリミング施設を登録',field('施設名','name',old?.name||'','text','required maxlength="100"')+field('電話番号（任意）','phone',old?.phone||'','tel')+field('住所（任意）','address',old?.address||'')+textarea('メモ（任意）','memo',old?.memo||'')+assignmentChecks(selected),f=>{const name=String(f.get('name')||'').trim(),pets=f.getAll('assignedPets');if(!name){toast('施設名を入力してください');return false}if(!pets.length){toast('登録する子を選んでください');return false}return saveCareChange(()=>{const value={id:old?.id||uid(),name,phone:f.get('phone'),address:f.get('address'),memo:f.get('memo'),pets};db.groomingFacilities=old?careFacilities().map(x=>x.id===old.id?value:x):[...careFacilities(),value]},'施設を保存しました')})}
function eventModal(id,defaultType='visit'){
 const old=db.events.find(e=>e.id===id),locked=!!old?.done.length;
 modal(old?'予定を編集':'予定を追加',select('予定の種類','type',careKinds,old?.type||defaultType)+`<div class="form-grid">${field('日付','date',old?.date||selectedDay,'date','required')}${field('予約時間（未定なら空欄）','time',old?.time||'','time')}</div><div id="event-hospital">${select('病院','hospital',[['','病院を選択'],...petHospitals().map(h=>[h.id,h.name])],old?.hospital||'')}</div><div id="event-facility">${select('トリミング施設','facility',[['','施設を選択'],...petCareFacilities().map(f=>[f.id,f.name])],old?.facility||'')}<p class="small muted">施設は「設定 → トリミング施設」で登録できます。</p></div><label>対象の子</label>${db.pets.map(p=>`<label class="check"><input name="pets" type="checkbox" value="${p.id}" ${(old?old.pets.includes(p.id):p.id===petId)?'checked':''} ${locked?'disabled':''}>${esc(p.name)}</label>`).join('')}${textarea('内容・持ち物など（任意）','memo',old?.memo||'')}`,f=>{
  const type=locked?(old.type||'visit'):f.get('type'),care=isGrooming({type}),pets=locked?old.pets:f.getAll('pets'),place=f.get(care?'facility':'hospital');
  if(!pets.length||!place){toast(care?'施設と対象の子を選んでください':'病院と対象の子を選んでください');return false}
  const value={...old,id:old?.id||uid(),type,date:f.get('date'),time:f.get('time'),pets,hospital:care?'':place,facility:care?place:'',memo:f.get('memo'),done:old?.done||[]};
  return saveCareChange(()=>{db.events=old?db.events.map(e=>e.id===old.id?value:e):[...db.events,value];selectedDay=value.date;month=value.date.slice(0,7)},'予定を保存しました');
 });
 const selectType=$('#f-type');selectType.disabled=locked;
 const update=()=>{const care=isGrooming({type:selectType.value});$('#event-hospital').hidden=care;$('#event-facility').hidden=!care;$('#f-hospital').disabled=care;$('#f-facility').disabled=!care};selectType.addEventListener('change',update);update();
}
function groomingRecordFields(old,date){return select('内容','type',careKinds.slice(1),old?.type||'trimming')+field('実際に行った日','date',old?.date||date,'date','required max="'+today()+'"')+field('時間（任意）','time',old?.time||'','time')+select('施設（任意）','facility',[['','未登録'],...petCareFacilities().map(f=>[f.id,f.name])],old?.facility||'')+textarea('メモ（任意）','memo',old?.memo||'')}
function validCareDate(date){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&date<=today()&&localDate(dateObj(date))===date}
function makeCareLog(f,pid,eventId,id){const type=f.get('type'),date=f.get('date'),facility=f.get('facility')||'';return{id:id||uid(),pet:pid,type,date,time:f.get('time')||'',facility,memo:f.get('memo')||'',eventId:eventId||'',detail:[facilityName(facility),f.get('memo')].filter(Boolean).join(' ／ ')}}
function groomingRecordModal(id){const old=db.logs.find(l=>l.id===id&&l.pet===petId&&isGrooming(l)),owner=petId;modal(old?'利用記録を編集':'トリミング・グルーミングを記録',`<p class="small muted">${esc(pname(owner))}の記録</p>`+groomingRecordFields(old,selectedDay>today()?today():selectedDay),f=>{if(!validCareDate(f.get('date'))){toast('今日までの正しい日付を入力してください');return false}return saveCareChange(()=>{const value=makeCareLog(f,owner,old?.eventId,old?.id);db.logs=old?db.logs.map(l=>l.id===old.id?value:l):[...db.logs,value];selectedDay=value.date;month=value.date.slice(0,7)},'利用した日を記録しました')})}
function completeGroomingEvent(ev){const pending=ev.pets.filter(pid=>!ev.done.includes(pid));if(!pending.length){toast('すでに利用済みです');return}modal('利用した日を記録',`<p class="small muted">${pending.map(pid=>esc(pname(pid))).join('・')}</p>`+groomingRecordFields({...ev,date:ev.date>today()?today():ev.date},today()),f=>{if(!validCareDate(f.get('date'))){toast('今日までの正しい日付を入力してください');return false}return saveCareChange(()=>{for(const pid of pending){db.logs.push(makeCareLog(f,pid,ev.id));ev.done.push(pid)}},'利用した日を記録しました')})}
function deleteGroomingRecord(log){modal('利用記録を取り消す','<p>この利用記録を取り消し、最終利用日を計算し直します。予定から登録した場合は、未完了の予定に戻ります。</p>',()=>saveCareChange(()=>{db.logs=db.logs.filter(l=>l.id!==log.id);const event=db.events.find(e=>e.id===log.eventId);if(event)event.done=event.done.filter(pid=>pid!==log.pet)},'利用記録を取り消しました'),'取り消す')}
function groomingDayRecords(date){const logs=db.logs.filter(l=>isGrooming(l)&&l.date===date&&(allPets||l.pet===petId));return logs.length?`<div class="sep"></div><h3>この日の利用記録</h3>${logs.map(l=>`<div class="hospital"><b>${eventLabel(l)} · ${esc(pname(l.pet))}</b><p class="small">${esc(l.time||'')} ${esc(l.detail)}</p>${l.pet===petId?action('groom-record','編集','link',`data-id="${l.id}"`):''}</div>`).join('')}`:''}
