// Local attachments are kept as original Blobs, separate from the text records.
let mediaDatabase;
const mediaURLs=new Set();
function mediaDB(){if(!mediaDatabase)mediaDatabase=new Promise((resolve,reject)=>{const req=indexedDB.open('komorebi-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('files',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>{mediaDatabase=null;reject(Error('写真・動画の保存場所を開けませんでした。ブラウザの設定を確認してください。'))}});return mediaDatabase}
async function mediaTransaction(mode,work){const database=await mediaDB();return new Promise((resolve,reject)=>{const tx=database.transaction('files',mode);let result;try{result=work(tx.objectStore('files'))}catch(e){tx.abort();reject(e);return}tx.oncomplete=()=>resolve(result?.result);tx.onerror=tx.onabort=()=>reject(Error('写真・動画を保存できませんでした。端末の空き容量を確認してください。'))})}
const mediaGet=id=>mediaTransaction('readonly',s=>s.get(id));
async function mediaDelete(ids){if(ids.length)await mediaTransaction('readwrite',s=>ids.forEach(id=>s.delete(id)))}
function attachmentType(file){return file.type?.startsWith('image/')?'image':file.type?.startsWith('video/')||/\.(mov|mp4|m4v|webm)$/i.test(file.name)?'video':null}
function validateMediaFiles(files){if(files.length>6)throw Error('一度に追加できる写真・動画は６件までです');for(const f of files){if(!attachmentType(f))throw Error('写真か動画を選んでください');if(f.size>100*1024*1024)throw Error('１件100MB以下にしてください。長い動画は必要な場面に分けてください。')}}
async function saveMediaFiles(files){files=files.filter(f=>f?.size);validateMediaFiles(files);const rows=files.map(f=>({id:uid(),name:f.name,type:attachmentType(f),mime:f.type||(attachmentType(f)==='video'?'video/quicktime':'image/jpeg'),size:f.size,blob:f.type?f:new Blob([f],{type:'video/quicktime'})}));if(rows.length)await mediaTransaction('readwrite',s=>rows.forEach(r=>s.put(r)));return rows.map(({blob,...meta})=>meta)}
function mediaPicker(){return field('発作時の写真・動画（任意）','attachments','','file','accept="image/*,video/*,.mov,.mp4,.m4v" multiple')+'<p class="small muted">撮影済みの写真や動画を選べます。１回６件・各100MBまで。元の画質でこの端末に保存します。</p><div id="media-selection" class="small" aria-live="polite"></div>'}
function mediaButton(l){const n=l.attachments?.length||0;return n?action('view-media',icon('photo')+`写真・動画 ${n}件`,'link',`data-id="${l.id}"`):''}
function releaseMediaURLs(){for(const u of mediaURLs)URL.revokeObjectURL(u);mediaURLs.clear()}
function mediaURL(blob){const u=URL.createObjectURL(blob);mediaURLs.add(u);return u}
async function viewMedia(logId){const log=db.logs.find(l=>l.id===logId&&l.pet===petId);if(!log)return;modal('発作時の写真・動画',`<p class="small muted">${fmt(log.date)} ${esc(log.time)}</p><div id="media-viewer">読み込み中…</div>`,()=>{},'閉じる');const target=$('#media-viewer');try{const rows=await Promise.all((log.attachments||[]).map(a=>mediaGet(a.id)));if(!target.isConnected)return;target.innerHTML=rows.map((r,i)=>{const a=log.attachments[i];if(!r)return`<p class="warn">${esc(a.name)}：添付が見つかりません。添付を含むバックアップから復元してください。</p>`;const url=mediaURL(r.blob);return`<figure class="attachment">${r.type==='video'?`<video controls playsinline preload="metadata" src="${url}" aria-label="${esc(r.name)}"></video>`:`<img src="${url}" alt="${esc(r.name)}">`}<figcaption>${esc(r.name)}<br><a href="${url}" download="${esc(r.name)}">元のファイルを保存</a></figcaption>${action('remove-media','この添付を削除','link',`data-id="${log.id}" data-media="${r.id}"`)}<p class="small muted">${r.type==='video'?'再生できない形式は、元のファイルを保存して端末で開いてください。':''}</p></figure>`}).join('')}catch(e){target.textContent=e.message}}
async function addMedia(logId){const log=db.logs.find(l=>l.id===logId&&l.pet===petId);if(!log)return;modal('発作の写真・動画を追加',mediaPicker(),async f=>{const refs=await saveMediaFiles(f.getAll('attachments'));if(!refs.length){toast('写真か動画を選んでね');return false}const old=log.attachments||[];log.attachments=[...old,...refs];if(!persist()){log.attachments=old;await mediaDelete(refs.map(r=>r.id));return false}render();toast('添付を保存しました')})}
const blobData=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('添付の読み込みに失敗しました'));r.readAsDataURL(blob)});
async function exportWithMedia(){toast('写真・動画を含むバックアップを準備しています');const snapshot=JSON.parse(JSON.stringify(db)),refs=[...snapshot.logs,...snapshot.notes].flatMap(l=>l.attachments||[]),attachments=[];for(const ref of refs){const row=await mediaGet(ref.id);if(!row)throw Error('見つからない添付があります。バックアップを作成できませんでした');attachments.push({...ref,data:await blobData(row.blob)})}const blob=new Blob([JSON.stringify({version:2,data:snapshot,attachments})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='uchinoko-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('添付を含むバックアップを作成しました')}
async function restoreWithMedia(loaded){validateBackup(loaded);const rows=[],mapping=new Map();if(loaded.version===2){if(!Array.isArray(loaded.attachments))throw Error('添付の形式が不正です');for(const a of loaded.attachments){if(typeof a.id!=='string'||typeof a.name!=='string'||typeof a.data!=='string'||!/^data:(image|video)\/[\w.+-]+;base64,/.test(a.data))throw Error('写真・動画の形式が不正です');const comma=a.data.indexOf(','),mime=a.data.slice(5,a.data.indexOf(';')),raw=atob(a.data.slice(comma+1));if(raw.length>100*1024*1024)throw Error('添付ファイルが大きすぎます');const id=uid(),blob=new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:mime});mapping.set(a.id,{id,name:a.name,type:mime.startsWith('video/')?'video':'image',mime,size:blob.size});rows.push({...mapping.get(a.id),blob})}}for(const l of [...loaded.data.logs,...loaded.data.notes]){if(l.attachments!==undefined&&!Array.isArray(l.attachments))throw Error('添付情報が不正です');l.attachments=(l.attachments||[]).map(a=>{const ref=mapping.get(a.id);if(!ref)throw Error('バックアップに添付ファイルが含まれていません');return ref})}if(rows.length)await mediaTransaction('readwrite',s=>rows.forEach(r=>s.put(r)));const previous=db;db=loaded.data;if(!persist()){db=previous;await mediaDelete(rows.map(r=>r.id));return false}petId=db.pets[0].id;slide=0;render();toast('写真・動画を含めて復元しました')}
document.addEventListener('change',e=>{if(e.target.id==='f-attachments'){const el=$('#media-selection');try{const files=Array.from(e.target.files);validateMediaFiles(files);el.textContent=files.map(f=>`${f.name}（${(f.size/1024/1024).toFixed(1)} MB）`).join(' / ')}catch(err){e.target.value='';el.textContent=err.message}}});
document.addEventListener('DOMContentLoaded',()=>$('#dialog').addEventListener('close',releaseMediaURLs));

function removeMedia(logId,mediaId){const log=db.logs.find(l=>l.id===logId&&l.pet===petId);if(!log)return;modal('添付を削除','<p>この写真・動画を手帖から削除します。発作の記録は残ります。</p>',async()=>{const old=log.attachments;log.attachments=old.filter(a=>a.id!==mediaId);if(!persist()){log.attachments=old;return false}render();try{await mediaDelete([mediaId])}catch{}toast('添付を削除しました')},'削除する')}
